ESPIDF = $(HOME)/projects/bofxbadge/micropython-esp-idf
#PORT = /dev/ttyUSB0
#FLASH_MODE = qio
#FLASH_SIZE = 4MB
#CROSS_COMPILE = xtensa-esp32-elf-
#SDKCONFIG = boards/sdkconfig.spiram
PYTHON=python2

include Makefile
